## 1번 : creation
### 문제
주어진 Python list L 을 이용하여 Numpy array로 변환하는 코드를 작성해보세요.

In [1]:
L = [1, 2, 3, 4, 5]

import numpy as np

L = np.array(L)
print(L)

[1 2 3 4 5]


## 2번 : creation (2)
### 문제
원소가 모두 0이고 크기가 10인 numpy array를 생성하는 코드를 작성해보세요.

In [2]:
import numpy as np

a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 3번 : creation (3)
### 문제
원소가 모두 32bytes 사이즈의 float 타입을 가지는 numpy array를 생성하는 코드를 작성해보세요.

In [3]:
L = [1.1, 2.2, 3.3, -4.4, 5.5]

np.array(L,dtype=np.float32)

array([ 1.1,  2.2,  3.3, -4.4,  5.5], dtype=float32)

## 4번 : creation (4)
### 문제
1부터 1000까지의 모든 정수를 원소로 하는 numpy array를 생성하는 코드를 작성해보세요.

In [4]:
np.arange(1,1001)

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

## 5번 : creation (5)
### 문제
0부터 1 사이의 실수를 0.1 간격으로 가지는 원소로 하는 numpy array를 생성하는 코드를 작성해보세요.

In [5]:
np.arange(0,1.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## 6번 : array data type
### 문제
numpy 라이브러리의 numpy array가 가질 수 있는 data type을 모두 서술해보세요.

numpy.bool_

bool

Boolean (True or False) stored as a byte

numpy.byte

signed char

Platform-defined

numpy.ubyte

unsigned char

Platform-defined

numpy.short

short

Platform-defined

numpy.ushort

unsigned short

Platform-defined

numpy.intc

int

Platform-defined

numpy.uintc

unsigned int

Platform-defined

numpy.int_

long

Platform-defined

numpy.uint

unsigned long

Platform-defined

numpy.longlong

long long

Platform-defined

numpy.ulonglong

unsigned long long

Platform-defined

numpy.half / numpy.float16

Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

numpy.single

float

Platform-defined single precision float: typically sign bit, 8 bits exponent, 23 bits mantissa

numpy.double

double

Platform-defined double precision float: typically sign bit, 11 bits exponent, 52 bits mantissa.

numpy.longdouble

long double

Platform-defined extended-precision float

numpy.csingle

float complex

Complex number, represented by two single-precision floats (real and imaginary components)

numpy.cdouble

double complex

Complex number, represented by two double-precision floats (real and imaginary components).

numpy.clongdouble

## 7번 : array data type (2)
### 문제
numpy array 내에서의 모든 원소가 **1) 동일한 data type**을 가져야 하는 이유와, 2) **동일한 data type을 가지는 것으로 python list에 비해 갖게되는 장점**에 대해 서술해보세요.

1. Numpy 행렬은 연속적인 메모리 위치에 저장된 동일한 데이터 타입의 집합이다. List는 비연속적인 메모리 위치에 저장된 동일한 데이터 타입의 집합

2. NumPy 패키지는 태스크를 여러 조각으로 나눈 다음 모든 조각을 병렬로 처리한다.

## 8번 : indexing
### 문제
주어진 numpy array의 두번째 원소를 찾아서 출력하는 코드를 작성해보세요.

In [7]:
import numpy as np

arr = np.array([31, 24, 37, 14, 25])
arr[1]

24

## 9번 : indexing (2)
### 문제
주어진 다차원 numpy array에서 두번째 행의 세번째 원소를 찾는 코드를 작성해보세요.

In [8]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2[1][2]

6

## 10번 : fancy indexing
### 문제
주어진 2차원 numpy array는 행렬을 나타냅니다.

주어진 행렬에서 첫번째 행과, 두번째 열을 출력하는 코드를 작성해보세요.

In [9]:
arr2 = np.array([ [10, 9, 8], [7, 6, 5], [4, 3, 2] ])

arr2[0]
arr2[:,1]

array([9, 6, 3])

## 11번 : array masking
### 문제
주어진 numpy array 에 대해서, 30보다 큰 숫자만 뽑는 코드를 작성하세요.
(단, 반복문을 통한 방법이 아닌 numpy array masking을 사용하세요.)

In [10]:
import numpy as np
import numpy.ma as ma

arr = np.array([30, 4, 550, 9, 112, 10000, 15, 21])
arr = ma.masked_greater(arr,30)
arr

masked_array(data=[30, 4, --, 9, --, --, 15, 21],
             mask=[False, False,  True, False,  True,  True, False, False],
       fill_value=999999)

## 12번 : max min
### 문제
주어진 numpy array의 최소/최대값을 찾아서 출력하는 코드를 작성해보세요.

In [11]:
arr = np.array([50, 1110, 1, 230, 3, 40, 517590, -41, -4959])

print(max(arr))
print(min(arr))

517590
-4959


## 13번 : max min indexing
### 문제
주어진 numpy array의 최소값과 최대값에 해당하는 원소의 index를 찾아서 출력하는 코드를 작성해보세요.

In [13]:
arr = np.array([1, 33, 5502, 221, -591, 0, -9, 50491])

print(arr.argmax())
print(arr.argmin())

7
4


## 14번 : concat
### 문제
주어진 두 개의 numpy array를 하나로 합치는 코드를 작성하세요.

In [14]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9])

arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 15번 : concat (2)
### 문제
주어진 1차원 numpy array 3개를 연결하여, 하나의 행렬을 구성하는 코드를 작성하세요.

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

np.vstack((arr1,arr2,arr3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 16번 : vector
### 문제
두개의 벡터  v1v1, v2v2가 numpy array로 주어졌을 때, 두 벡터의 합 v1+v2v1+v2 을 구하는 코드를 작성하세요.

In [16]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, -1, 2])

v1+v2

array([5, 1, 5])

## 17번 : vector (2)
### 문제
두개의 벡터 v1, v2v1,v2가 numpy array로 주어졌을 때, 두 벡터의 내적 v1 ⋅ v2v1⋅v2 을 구하는 코드를 작성하세요.

In [17]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, -1, 2])

np.dot(v1,v2)
np.inner(v1,v2)

8

## 18번 : broadcasting
### 문제
주어진 numpy array의 모든 원소에 각각 3을 더하는 코드를 작성하세요.

In [18]:
arr1 = np.array([1, 2, 3])
arr1+3

array([4, 5, 6])

## 19번 : broadcasting (2)
### 문제
numpy array로 표현된 행렬에 모든 행에 같은 벡터를 더하는 연산을 수행하는 코드를 작성하세요.

In [19]:
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v1 = np.array([-1, -2, -3])

mat1 + v1

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

## 20번 : reshaping
### 문제
이미지 데이터를 처리할 때, numpy array를 통해서 이미지 데이터를 표현하면 "가로 pixel X 세로 pixel" 크기의 numpy array가 됩니다.
***5x5의 크기를 가지는 이미지가 numpy array로 표현***되었을 때, 이를 1차원 벡터로 변환하는 코드를 작성해보세요.

In [20]:
img = np.random.random((5, 5))
img
np.reshape(img,(1,-1))

array([[0.74555229, 0.54595301, 0.01296621, 0.0033709 , 0.26773882,
        0.33265466, 0.74286587, 0.52474453, 0.2025602 , 0.45177781,
        0.07175573, 0.04588806, 0.11764906, 0.3813456 , 0.28229457,
        0.55239003, 0.20598034, 0.53643619, 0.63726016, 0.71918814,
        0.05734998, 0.82943396, 0.65098411, 0.63785621, 0.93850151]])

## 21번 : reshaping (2)
### 문제
행의 개수를 모르는 행렬이 있다고 할 때, 이 행렬을 1차원 벡터로 변환하는 코드를 작성하세요.

In [21]:
N = int(input("N? : ")) # 사용자 입력으로 받은 자연수 N
data = np.random.random((N, 6)) # N x 6 matrix
np.reshape(data,(1,-1))

N? : 3


array([[0.54152784, 0.65585423, 0.09341713, 0.25177748, 0.51727302,
        0.53355753, 0.80879634, 0.38362563, 0.47845019, 0.32532726,
        0.48697782, 0.81521124, 0.62587269, 0.88675536, 0.65082192,
        0.02744626, 0.00250697, 0.5437104 ]])

## 22번 : math function
### 문제
사용자에게 입력받은 정수 x에 대한 sine(sinsin), cosine(coscos), tangent(tantan) 함수 값을 구하는 코드를 작성해보세요.
(단, numpy 라이브러리 함수를 이용하세요.)

In [22]:
x = int(input("Number? : "))

print("sin({}) : {}".format(x, np.sin(x)))
print("cos({}) : {}".format(x, np.cos(x)))
print("tan({}) : {}".format(x, np.tan(x)))

Number? : 10
sin(10) : -0.5440211108893698
cos(10) : -0.8390715290764524
tan(10) : 0.6483608274590866


## 23번 : math function (2)
### 문제
사용자에게 입력받은 실수에 대한 절대값(*absabs*), 제곱근(*sqrtsqrt*), 제곱(*squaresquare*) 값을 구하는 코드를 작성해보세요.

(단, numpy 라이브러리 함수를 이용하세요.)

In [23]:
x = float(input("Number? : "))


np.abs(x)
x**2
np.sqrt(x)

Number? : 3.14


1.772004514666935

##24번 : math function (3)
### 문제
사용자에게 입력받은 양수logx 의 정의역 xx는 양수로 정의됩니다.)인 실수 x에 대하여 e^x, logx 값을 구하는 코드를 작성해보세요.

In [24]:
x = np.abs(float(input("Number? : ")))

np.exp(x)
np.log(x)

Number? : 3.14


1.144222799920162

## 25번 : sorting
### 문제
주어진 numpy array를 오름차순 정렬하는 코드를 작성해보세요.

In [25]:
arr = np.array([1, -5, 3.4, 55.41, -1009, 2245, -575, -1935.124])

arr1 = np.sort(arr)

## 26번 : sorting (2)
### 문제
다음 numpy array를 대하여 오름차순으로 정렬한 뒤의 array에서 각 원소가 가지는 인덱스를 구하는 코드를 작성하세요.

(단, 주어진 배열을 변형하지 말고 사용하세요.)

In [27]:
arr = np.array([1, -5, 3.4, 55.41, -1009, 2245, -575, -1935.124])

np.argsort(arr)

array([7, 4, 6, 1, 0, 2, 3, 5])

## 27번 : sorting (3)
### 문제
행렬 형태로 주어진 numpy array를 행별로 오름차순 정렬하는 코드를 작성해보세요.

In [28]:
mat = np.array([[1, -1, 3],
        [4, 3, -6],
        [0, 11, 9]])

np.sort(mat, axis = 1)

array([[-1,  1,  3],
       [-6,  3,  4],
       [ 0,  9, 11]])

## 28번 : sorting (4)
### 문제
행렬 형태로 주어진 numpy array를 열별로 내림차순 정렬하는 코드를 작성해보세요.

In [29]:
mat = np.array([[1, -1, 3],
        [4, 3, -6],
        [0, 11, 9]])


np.sort(mat, axis = 0)[::-1]

array([[ 4, 11,  9],
       [ 1,  3,  3],
       [ 0, -1, -6]])